import { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // Chest
  { id: 'chest_001', name: { tr: 'Bench Press (Barbell)', en: 'Bench Press (Barbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_002', name: { tr: 'Bench Press (Dumbbell)', en: 'Bench Press (Dumbbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_003', name: { tr: 'Incline Bench Press (Barbell)', en: 'Incline Bench Press (Barbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_004', name: { tr: 'Incline Bench Press (Dumbbell)', en: 'Incline Bench Press (Dumbbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_005', name: { tr: 'Decline Bench Press (Barbell)', en: 'Decline Bench Press (Barbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_006', name: { tr: 'Decline Bench Press (Dumbbell)', en: 'Decline Bench Press (Dumbbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_007', name: { tr: 'Chest Press (Machine)', en: 'Chest Press (Machine)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_008', name: { tr: 'Incline Chest Press (Machine)', en: 'Incline Chest Press (Machine)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_009', name: { tr: 'Pec Deck Fly', en: 'Pec Deck Fly' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_010', name: { tr: 'Cable Crossover', en: 'Cable Crossover' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_011', name: { tr: 'High Cable Fly', en: 'High Cable Fly' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_012', name: { tr: 'Low Cable Fly', en: 'Low Cable Fly' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_013', name: { tr: 'Dumbbell Fly', en: 'Dumbbell Fly' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_014', name: { tr: 'Incline Dumbbell Fly', en: 'Incline Dumbbell Fly' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_015', name: { tr: 'Push Up', en: 'Push Up' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_016', name: { tr: 'Weighted Push Up', en: 'Weighted Push Up' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_017', name: { tr: 'Diamond Push Up', en: 'Diamond Push Up' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_018', name: { tr: 'Dips (Chest Focus)', en: 'Dips (Chest Focus)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_019', name: { tr: 'Pullover (Dumbbell)', en: 'Pullover (Dumbbell)' }, muscle: { tr: 'Göğüs', en: 'Chest' } },
  { id: 'chest_020', name: { tr: 'Svend Press', en: 'Svend Press' }, muscle: { tr: 'Göğüs', en: 'Chest' } },

  // Back
  { id: 'back_001', name: { tr: 'Deadlift (Barbell)', en: 'Deadlift (Barbell)' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_002', name: { tr: 'Pull Up', en: 'Pull Up' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_003', name: { tr: 'Chin Up', en: 'Chin Up' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_004', name: { tr: 'Lat Pulldown (Cable)', en: 'Lat Pulldown (Cable)' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_005', name: { tr: 'Close Grip Lat Pulldown', en: 'Close Grip Lat Pulldown' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_006', name: { tr: 'Straight Arm Pulldown', en: 'Straight Arm Pulldown' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_007', name: { tr: 'Bent Over Row (Barbell)', en: 'Bent Over Row (Barbell)' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_008', name: { tr: 'One Arm Row (Dumbbell)', en: 'One Arm Row (Dumbbell)' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_009', name: { tr: 'Seated Cable Row', en: 'Seated Cable Row' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_010', name: { tr: 'T-Bar Row', en: 'T-Bar Row' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_011', name: { tr: 'Chest Supported Row', en: 'Chest Supported Row' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_012', name: { tr: 'Machine Row', en: 'Machine Row' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_013', name: { tr: 'Inverted Row', en: 'Inverted Row' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_014', name: { tr: 'Back Extension', en: 'Back Extension' }, muscle: { tr: 'Sırt', en: 'Back' } },
  { id: 'back_015', name: { tr: 'Rack Pull', en: 'Rack Pull' }, muscle: { tr: 'Sırt', en: 'Back' } },

  // Legs
  { id: 'legs_001', name: { tr: 'Squat (Barbell)', en: 'Squat (Barbell)' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_002', name: { tr: 'Front Squat', en: 'Front Squat' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_003', name: { tr: 'Hack Squat', en: 'Hack Squat' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_004', name: { tr: 'Leg Press', en: 'Leg Press' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_005', name: { tr: 'Romanian Deadlift (Barbell)', en: 'Romanian Deadlift (Barbell)' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_006', name: { tr: 'Romanian Deadlift (Dumbbell)', en: 'Romanian Deadlift (Dumbbell)' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_007', name: { tr: 'Bulgarian Split Squat', en: 'Bulgarian Split Squat' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_008', name: { tr: 'Walking Lunge', en: 'Walking Lunge' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_009', name: { tr: 'Leg Extension', en: 'Leg Extension' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_010', name: { tr: 'Leg Curl (Lying)', en: 'Leg Curl (Lying)' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_011', name: { tr: 'Seated Leg Curl', en: 'Seated Leg Curl' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_012', name: { tr: 'Hip Thrust (Barbell)', en: 'Hip Thrust (Barbell)' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_013', name: { tr: 'Glute Bridge', en: 'Glute Bridge' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_014', name: { tr: 'Standing Calf Raise', en: 'Standing Calf Raise' }, muscle: { tr: 'Bacak', en: 'Legs' } },
  { id: 'legs_015', name: { tr: 'Seated Calf Raise', en: 'Seated Calf Raise' }, muscle: { tr: 'Bacak', en: 'Legs' } },

  // Shoulders
  { id: 'shoulders_001', name: { tr: 'Overhead Press (Barbell)', en: 'Overhead Press (Barbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_002', name: { tr: 'Overhead Press (Dumbbell)', en: 'Overhead Press (Dumbbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_003', name: { tr: 'Arnold Press', en: 'Arnold Press' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_004', name: { tr: 'Lateral Raise (Dumbbell)', en: 'Lateral Raise (Dumbbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_005', name: { tr: 'Cable Lateral Raise', en: 'Cable Lateral Raise' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_006', name: { tr: 'Front Raise', en: 'Front Raise' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_007', name: { tr: 'Rear Delt Fly (Dumbbell)', en: 'Rear Delt Fly (Dumbbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_008', name: { tr: 'Reverse Pec Deck', en: 'Reverse Pec Deck' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_009', name: { tr: 'Face Pull (Cable)', en: 'Face Pull (Cable)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_010', name: { tr: 'Upright Row', en: 'Upright Row' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_011', name: { tr: 'Shrug (Dumbbell)', en: 'Shrug (Dumbbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },
  { id: 'shoulders_012', name: { tr: 'Shrug (Barbell)', en: 'Shrug (Barbell)' }, muscle: { tr: 'Omuz', en: 'Shoulders' } },

  // Arms
  { id: 'arms_001', name: { tr: 'Bicep Curl (Dumbbell)', en: 'Bicep Curl (Dumbbell)' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_002', name: { tr: 'Bicep Curl (Barbell)', en: 'Bicep Curl (Barbell)' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_003', name: { tr: 'Hammer Curl (Dumbbell)', en: 'Hammer Curl (Dumbbell)' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_004', name: { tr: 'Incline Dumbbell Curl', en: 'Incline Dumbbell Curl' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_005', name: { tr: 'Preacher Curl', en: 'Preacher Curl' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_006', name: { tr: 'Cable Curl', en: 'Cable Curl' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_007', name: { tr: 'Tricep Pushdown (Cable)', en: 'Tricep Pushdown (Cable)' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_008', name: { tr: 'Tricep Extension (Cable)', en: 'Tricep Extension (Cable)' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_009', name: { tr: 'Overhead Tricep Extension', en: 'Overhead Tricep Extension' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_010', name: { tr: 'Skull Crusher', en: 'Skull Crusher' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_011', name: { tr: 'Close Grip Bench Press', en: 'Close Grip Bench Press' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_012', name: { tr: 'Tricep Dips', en: 'Tricep Dips' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_013', name: { tr: 'Wrist Curl', en: 'Wrist Curl' }, muscle: { tr: 'Kol', en: 'Arms' } },
  { id: 'arms_014', name: { tr: 'Reverse Curl', en: 'Reverse Curl' }, muscle: { tr: 'Kol', en: 'Arms' } },

  // Core
  { id: 'core_001', name: { tr: 'Crunch', en: 'Crunch' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_002', name: { tr: 'Plank', en: 'Plank' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_003', name: { tr: 'Side Plank', en: 'Side Plank' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_004', name: { tr: 'Leg Raise', en: 'Leg Raise' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_005', name: { tr: 'Hanging Leg Raise', en: 'Hanging Leg Raise' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_006', name: { tr: 'Cable Crunch', en: 'Cable Crunch' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_007', name: { tr: 'Russian Twist', en: 'Russian Twist' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_008', name: { tr: 'Ab Wheel Rollout', en: 'Ab Wheel Rollout' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_009', name: { tr: 'Mountain Climber', en: 'Mountain Climber' }, muscle: { tr: 'Merkez', en: 'Core' } },
  { id: 'core_010', name: { tr: 'Pallof Press', en: 'Pallof Press' }, muscle: { tr: 'Merkez', en: 'Core' } },

  // Cardio
  { id: 'cardio_001', name: { tr: 'Koşu Bandı', en: 'Treadmill' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_002', name: { tr: 'Bisiklet', en: 'Bike' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_003', name: { tr: 'Kürek', en: 'Rowing' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_004', name: { tr: 'Eliptik', en: 'Elliptical' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_005', name: { tr: 'İp Atlama', en: 'Jump Rope' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_006', name: { tr: 'Stair Climber', en: 'Stair Climber' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_007', name: { tr: 'Assault Bike', en: 'Assault Bike' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } },
  { id: 'cardio_008', name: { tr: 'Sled Push', en: 'Sled Push' }, muscle: { tr: 'Kardiyo', en: 'Cardio' } }
];
